apiVersion: v1
kind: Pod
metadata:
  name: reference-burstable
spec:
  containers:
    - name: reference
      image: "registry.k8s.io/pause:3.9"
      resources:
        requests:
          cpu: "999m"
          memory: "1Gi"
