apiVersion: v1
kind: Pod
metadata:
  generateName: pod-lowlat-minimal-
spec:
  containers:
    - name: workload-container
      image: "registry.k8s.io/pause:3.9"
      resources:
        limits:
          cpu: "2"
          memory: "4Gi"
        claims:
          - name: "lowlat-resources-minimal"
  resourceClaims:
    - name: "lowlat-resources-minimal"
      resourceClaimTemplateName: "lowlat-minimal" 

