apiVersion: v1
kind: Pod
metadata:
  generateName: pod-lowlat-minimal-
spec:
  containers:
    - name: workload-container
      image: "dev.kind.local/dra/dra-core-resource-validation:dev"
      imagePullPolicy: IfNotPresent
      resources:
        limits:
          cpu: "2"
          memory: "4Gi"
        claims:
          - name: "lowlat-resources-minimal"
  resourceClaims:
    - name: "lowlat-resources-minimal"
      resourceClaimTemplateName: "lowlat-minimal" 

