apiVersion: resource.k8s.io/v1
kind: ResourceClaimTemplate
metadata:
  name: lowlat-minimal
spec:
  spec:
    devices:
      requests:
      - name: mem
        exactly:
          deviceClassName: dra.memory
          capacity:
            requests:
              size: 1Gi
      - name: cpu
        exactly:
          deviceClassName: dra.cpu
          capacity:
            requests:
              dra.cpu/cpu: "1"
