apiVersion: v1
kind: Pod
metadata:
  name: pod-lowlat-tiny
spec:
  containers:
    - name: workload-container
      image: "dev.kind.local/dra/dra-core-resource-validation:dev"
      imagePullPolicy: IfNotPresent
      resources:
        limits:
          cpu: "2"
          memory: "4Gi"
        claims:
          - name: "lowlat-resources-tiny"
  resourceClaims:
    - name: "lowlat-resources-tiny"
      resourceClaimTemplateName: "lowlat-tiny" 

